#PBS -N cs6210-proj2__mpi_dissemination_barrier__mpinodes_6.pbs
#PBS -l nodes=6:ppn=1
#PBS -l pmem=1gb
#PBS -l walltime=00:10:00
#PBS -q pace-ice
#PBS -j oe
#PBS -o mpi_dissemination_barrier__mpinodes_6.out


echo "Started on `/bin/hostname`"
echo "Nodes chosen are:"
cat $PBS_NODEFILE


module load gcc/8.3.0
module load mvapich2/2.3.2


cd /storage/home/hpaceice1/dkadiyala3/project2/FINAL/mpi_dissemination_barrier/run1
mpic++ -g -Wall mpi_dissemination_barrier.cpp -o mpi_dissemination_barrier__mpinodes_6
mpirun -np 6 ./mpi_dissemination_barrier__mpinodes_6
