#PBS -N cs6210-proj2__omp_sense-reverse_barrier__ompthreads_7.pbs
#PBS -l nodes=1:ppn=7
#PBS -l pmem=1gb
#PBS -l walltime=00:10:00
#PBS -q pace-ice
#PBS -j oe
#PBS -o omp_sense-reverse_barrier__ompthreads_7.out


echo "Started on `/bin/hostname`"
echo "Nodes chosen are:"
cat $PBS_NODEFILE


module load gcc/8.3.0
export OMP_NUM_THREADS=7


cd /storage/home/hpaceice1/dkadiyala3/project2/FINAL/omp_sense-reverse_barrier/run1
g++ -g -Wall -fopenmp omp_sense-reverse_barrier.cpp -o omp_sense-reverse_barrier__ompthreads_7
./omp_sense-reverse_barrier__ompthreads_7 7 
